# Generated by Django 5.0.3 on 2024-04-24 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_initiator_set', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_target_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('initiator', 'target')},
            },
        ),
    ]
