# Generated by Django 5.0.3 on 2024-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establish_date',
            field=models.IntegerField(),
        ),
    ]
