# Generated by Django 5.0.3 on 2024-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
